language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
install:
  - echo "no dependencies to install"
script:
  - python setup.py build
  - python setup.py test
  - python setup.py test_kat
  - python setup.py speed
